version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7
    container_name: mock-interview-db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - interview-network

  # Backend Service
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: mock-interview-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/mockInterview?authSource=admin
      - JWT_SECRET=your_super_secret_jwt_key_here_make_it_long_and_complex
      - PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - interview-network
    volumes:
      - ./server:/app
      - /app/node_modules

  # Frontend Service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: mock-interview-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - interview-network
    environment:
      - REACT_APP_API_URL=http://localhost:5000

volumes:
  mongodb_data:

networks:
  interview-network:
    driver: bridge